model_list:
  - model_name: gemini-2.5-pro
      litellm_params:
        model: gemini/gemini-2.5-pro-preview-03-25
        api_key: "os.environ/GEMINI_API_KEY"
  - model_name: gemini-2.5-flash
    litellm_params:
      model: gemini/gemini-2.5-flash-preview-04-17
      api_key: "os.environ/GEMINI_API_KEY"